"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GroupByUserResolver = exports.AggregateUserResolver = exports.UpsertUserResolver = exports.UpdateManyUserResolver = exports.DeleteManyUserResolver = exports.UpdateUserResolver = exports.DeleteUserResolver = exports.CreateUserResolver = exports.FindManyUserResolver = exports.FindFirstUserResolver = exports.FindUniqueUserResolver = exports.GroupByOrganizationResolver = exports.AggregateOrganizationResolver = exports.UpsertOrganizationResolver = exports.UpdateManyOrganizationResolver = exports.DeleteManyOrganizationResolver = exports.UpdateOrganizationResolver = exports.DeleteOrganizationResolver = exports.CreateOrganizationResolver = exports.FindManyOrganizationResolver = exports.FindFirstOrganizationResolver = exports.FindUniqueOrganizationResolver = void 0;
var FindUniqueOrganizationResolver_1 = require("./Organization/FindUniqueOrganizationResolver");
Object.defineProperty(exports, "FindUniqueOrganizationResolver", { enumerable: true, get: function () { return FindUniqueOrganizationResolver_1.FindUniqueOrganizationResolver; } });
var FindFirstOrganizationResolver_1 = require("./Organization/FindFirstOrganizationResolver");
Object.defineProperty(exports, "FindFirstOrganizationResolver", { enumerable: true, get: function () { return FindFirstOrganizationResolver_1.FindFirstOrganizationResolver; } });
var FindManyOrganizationResolver_1 = require("./Organization/FindManyOrganizationResolver");
Object.defineProperty(exports, "FindManyOrganizationResolver", { enumerable: true, get: function () { return FindManyOrganizationResolver_1.FindManyOrganizationResolver; } });
var CreateOrganizationResolver_1 = require("./Organization/CreateOrganizationResolver");
Object.defineProperty(exports, "CreateOrganizationResolver", { enumerable: true, get: function () { return CreateOrganizationResolver_1.CreateOrganizationResolver; } });
var DeleteOrganizationResolver_1 = require("./Organization/DeleteOrganizationResolver");
Object.defineProperty(exports, "DeleteOrganizationResolver", { enumerable: true, get: function () { return DeleteOrganizationResolver_1.DeleteOrganizationResolver; } });
var UpdateOrganizationResolver_1 = require("./Organization/UpdateOrganizationResolver");
Object.defineProperty(exports, "UpdateOrganizationResolver", { enumerable: true, get: function () { return UpdateOrganizationResolver_1.UpdateOrganizationResolver; } });
var DeleteManyOrganizationResolver_1 = require("./Organization/DeleteManyOrganizationResolver");
Object.defineProperty(exports, "DeleteManyOrganizationResolver", { enumerable: true, get: function () { return DeleteManyOrganizationResolver_1.DeleteManyOrganizationResolver; } });
var UpdateManyOrganizationResolver_1 = require("./Organization/UpdateManyOrganizationResolver");
Object.defineProperty(exports, "UpdateManyOrganizationResolver", { enumerable: true, get: function () { return UpdateManyOrganizationResolver_1.UpdateManyOrganizationResolver; } });
var UpsertOrganizationResolver_1 = require("./Organization/UpsertOrganizationResolver");
Object.defineProperty(exports, "UpsertOrganizationResolver", { enumerable: true, get: function () { return UpsertOrganizationResolver_1.UpsertOrganizationResolver; } });
var AggregateOrganizationResolver_1 = require("./Organization/AggregateOrganizationResolver");
Object.defineProperty(exports, "AggregateOrganizationResolver", { enumerable: true, get: function () { return AggregateOrganizationResolver_1.AggregateOrganizationResolver; } });
var GroupByOrganizationResolver_1 = require("./Organization/GroupByOrganizationResolver");
Object.defineProperty(exports, "GroupByOrganizationResolver", { enumerable: true, get: function () { return GroupByOrganizationResolver_1.GroupByOrganizationResolver; } });
var FindUniqueUserResolver_1 = require("./User/FindUniqueUserResolver");
Object.defineProperty(exports, "FindUniqueUserResolver", { enumerable: true, get: function () { return FindUniqueUserResolver_1.FindUniqueUserResolver; } });
var FindFirstUserResolver_1 = require("./User/FindFirstUserResolver");
Object.defineProperty(exports, "FindFirstUserResolver", { enumerable: true, get: function () { return FindFirstUserResolver_1.FindFirstUserResolver; } });
var FindManyUserResolver_1 = require("./User/FindManyUserResolver");
Object.defineProperty(exports, "FindManyUserResolver", { enumerable: true, get: function () { return FindManyUserResolver_1.FindManyUserResolver; } });
var CreateUserResolver_1 = require("./User/CreateUserResolver");
Object.defineProperty(exports, "CreateUserResolver", { enumerable: true, get: function () { return CreateUserResolver_1.CreateUserResolver; } });
var DeleteUserResolver_1 = require("./User/DeleteUserResolver");
Object.defineProperty(exports, "DeleteUserResolver", { enumerable: true, get: function () { return DeleteUserResolver_1.DeleteUserResolver; } });
var UpdateUserResolver_1 = require("./User/UpdateUserResolver");
Object.defineProperty(exports, "UpdateUserResolver", { enumerable: true, get: function () { return UpdateUserResolver_1.UpdateUserResolver; } });
var DeleteManyUserResolver_1 = require("./User/DeleteManyUserResolver");
Object.defineProperty(exports, "DeleteManyUserResolver", { enumerable: true, get: function () { return DeleteManyUserResolver_1.DeleteManyUserResolver; } });
var UpdateManyUserResolver_1 = require("./User/UpdateManyUserResolver");
Object.defineProperty(exports, "UpdateManyUserResolver", { enumerable: true, get: function () { return UpdateManyUserResolver_1.UpdateManyUserResolver; } });
var UpsertUserResolver_1 = require("./User/UpsertUserResolver");
Object.defineProperty(exports, "UpsertUserResolver", { enumerable: true, get: function () { return UpsertUserResolver_1.UpsertUserResolver; } });
var AggregateUserResolver_1 = require("./User/AggregateUserResolver");
Object.defineProperty(exports, "AggregateUserResolver", { enumerable: true, get: function () { return AggregateUserResolver_1.AggregateUserResolver; } });
var GroupByUserResolver_1 = require("./User/GroupByUserResolver");
Object.defineProperty(exports, "GroupByUserResolver", { enumerable: true, get: function () { return GroupByUserResolver_1.GroupByUserResolver; } });
