"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.UpsertOrganizationArgs = exports.UpdateOrganizationArgs = exports.UpdateManyOrganizationArgs = exports.GroupByOrganizationArgs = exports.FindUniqueOrganizationArgs = exports.FindManyOrganizationArgs = exports.FindFirstOrganizationArgs = exports.DeleteOrganizationArgs = exports.DeleteManyOrganizationArgs = exports.CreateOrganizationArgs = exports.AggregateOrganizationArgs = void 0;
var AggregateOrganizationArgs_1 = require("./AggregateOrganizationArgs");
Object.defineProperty(exports, "AggregateOrganizationArgs", { enumerable: true, get: function () { return AggregateOrganizationArgs_1.AggregateOrganizationArgs; } });
var CreateOrganizationArgs_1 = require("./CreateOrganizationArgs");
Object.defineProperty(exports, "CreateOrganizationArgs", { enumerable: true, get: function () { return CreateOrganizationArgs_1.CreateOrganizationArgs; } });
var DeleteManyOrganizationArgs_1 = require("./DeleteManyOrganizationArgs");
Object.defineProperty(exports, "DeleteManyOrganizationArgs", { enumerable: true, get: function () { return DeleteManyOrganizationArgs_1.DeleteManyOrganizationArgs; } });
var DeleteOrganizationArgs_1 = require("./DeleteOrganizationArgs");
Object.defineProperty(exports, "DeleteOrganizationArgs", { enumerable: true, get: function () { return DeleteOrganizationArgs_1.DeleteOrganizationArgs; } });
var FindFirstOrganizationArgs_1 = require("./FindFirstOrganizationArgs");
Object.defineProperty(exports, "FindFirstOrganizationArgs", { enumerable: true, get: function () { return FindFirstOrganizationArgs_1.FindFirstOrganizationArgs; } });
var FindManyOrganizationArgs_1 = require("./FindManyOrganizationArgs");
Object.defineProperty(exports, "FindManyOrganizationArgs", { enumerable: true, get: function () { return FindManyOrganizationArgs_1.FindManyOrganizationArgs; } });
var FindUniqueOrganizationArgs_1 = require("./FindUniqueOrganizationArgs");
Object.defineProperty(exports, "FindUniqueOrganizationArgs", { enumerable: true, get: function () { return FindUniqueOrganizationArgs_1.FindUniqueOrganizationArgs; } });
var GroupByOrganizationArgs_1 = require("./GroupByOrganizationArgs");
Object.defineProperty(exports, "GroupByOrganizationArgs", { enumerable: true, get: function () { return GroupByOrganizationArgs_1.GroupByOrganizationArgs; } });
var UpdateManyOrganizationArgs_1 = require("./UpdateManyOrganizationArgs");
Object.defineProperty(exports, "UpdateManyOrganizationArgs", { enumerable: true, get: function () { return UpdateManyOrganizationArgs_1.UpdateManyOrganizationArgs; } });
var UpdateOrganizationArgs_1 = require("./UpdateOrganizationArgs");
Object.defineProperty(exports, "UpdateOrganizationArgs", { enumerable: true, get: function () { return UpdateOrganizationArgs_1.UpdateOrganizationArgs; } });
var UpsertOrganizationArgs_1 = require("./UpsertOrganizationArgs");
Object.defineProperty(exports, "UpsertOrganizationArgs", { enumerable: true, get: function () { return UpsertOrganizationArgs_1.UpsertOrganizationArgs; } });
